# Generated by Django 4.0.1 on 2022-01-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdjustApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='date',
            field=models.CharField(max_length=12),
        ),
    ]
